# Generated by Django 4.1.7 on 2023-04-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foto_geral',
            new_name='FotoGeral',
        ),
    ]
